[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PDDL4J Exercices"
authors = [{name = "Humbert Fiorino", email = "humbert.fiorino@imag.fr"}]
dynamic = ["version", "description"]
